runtime: nodejs
env: flex
runtime_config:
    operating_system: "ubuntu22"
    runtime_version: "20"

handlers:
- url: /.*
  secure: always
  redirect_http_response_code: 301
  script: auto
- url: /*
  secure: always
  redirect_http_response_code: 301
  script: auto

automatic_scaling:
  min_num_instances: 1
  max_num_instances: 3
  cool_down_period_sec: 150
  cpu_utilization:
    target_utilization: 0.80

resources:
  cpu: 1
  memory_gb: 0.5
  disk_size_gb: 10

env_variables:
  NODE_ENV: 'production'
  NEXT_PUBLIC_API_URL: 'http://127.0.0.1/api/''
